/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "quadrado.h"

int *
quadrado_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("A função quadrado foi chamada para o numero (%d)",argp->a);
	fflush(stdout);
	result = argp->a * argp->a;
	return &result;
}
